export const WHISPER_MODELS = [
  {
    id: "mlx-community/whisper-tiny",
    label: "Tiny (fastest, lowest accuracy)",
  },
  {
    id: "mlx-community/whisper-medium-mlx",
    label: "Medium (balanced)",
  },
  {
    id: "mlx-community/whisper-large-v3-mlx",
    label: "Large V3 (best quality)",
  },
  {
    id: "mlx-community/whisper-large-v3-turbo",
    label: "Large V3 Turbo (fast)",
  },
  {
    id: "mlx-community/distil-whisper-large-v3",
    label: "Distil Large V3 (fast)",
  },
  {
    id: "mlx-community/whisper-large-v3-turbo-q4",
    label: "Large V3 Turbo Q4 (lower memory)",
  },
];

export const WHISPER_LANGUAGES = [
  { id: "ar", label: "Arabic" },
  { id: "bn", label: "Bengali" },
  { id: "cs", label: "Czech" },
  { id: "da", label: "Danish" },
  { id: "de", label: "German" },
  { id: "el", label: "Greek" },
  { id: "en", label: "English" },
  { id: "es", label: "Spanish" },
  { id: "fa", label: "Persian" },
  { id: "fi", label: "Finnish" },
  { id: "fr", label: "French" },
  { id: "hi", label: "Hindi" },
  { id: "hu", label: "Hungarian" },
  { id: "id", label: "Indonesian" },
  { id: "it", label: "Italian" },
  { id: "ja", label: "Japanese" },
  { id: "ko", label: "Korean" },
  { id: "nl", label: "Dutch" },
  { id: "pl", label: "Polish" },
  { id: "pt", label: "Portuguese" },
  { id: "ro", label: "Romanian" },
  { id: "ru", label: "Russian" },
  { id: "sk", label: "Slovak" },
  { id: "sv", label: "Swedish" },
  { id: "th", label: "Thai" },
  { id: "tr", label: "Turkish" },
  { id: "uk", label: "Ukrainian" },
  { id: "ur", label: "Urdu" },
  { id: "vi", label: "Vietnamese" },
  { id: "zh", label: "Chinese" },
];

export const TTS_MODELS = [
  {
    id: "mlx-community/Kokoro-82M-bf16",
    label: "Kokoro 82M (MLX)",
  },
  {
    id: "Marvis-AI/marvis-tts-250m-v0.1",
    label: "Marvis 250M (MLX)",
  },
];

export const TTS_LANGUAGES = [
  { id: "en-US", label: "American English" },
  { id: "en-GB", label: "British English" },
  { id: "ja", label: "Japanese" },
  { id: "zh", label: "Mandarin Chinese" },
  { id: "es", label: "Spanish" },
  { id: "fr", label: "French" },
  { id: "hi", label: "Hindi" },
  { id: "it", label: "Italian" },
  { id: "pt-BR", label: "Brazilian Portuguese" },
];

export const KOKORO_VOICES = [
  { id: "af_heart", label: "af_heart", language: "en-US" },
  { id: "af_alloy", label: "af_alloy", language: "en-US" },
  { id: "af_aoede", label: "af_aoede", language: "en-US" },
  { id: "af_bella", label: "af_bella", language: "en-US" },
  { id: "af_jessica", label: "af_jessica", language: "en-US" },
  { id: "af_kore", label: "af_kore", language: "en-US" },
  { id: "af_nicole", label: "af_nicole", language: "en-US" },
  { id: "af_nova", label: "af_nova", language: "en-US" },
  { id: "af_river", label: "af_river", language: "en-US" },
  { id: "af_sarah", label: "af_sarah", language: "en-US" },
  { id: "af_sky", label: "af_sky", language: "en-US" },
  { id: "am_adam", label: "am_adam", language: "en-US" },
  { id: "am_echo", label: "am_echo", language: "en-US" },
  { id: "am_eric", label: "am_eric", language: "en-US" },
  { id: "am_fenrir", label: "am_fenrir", language: "en-US" },
  { id: "am_liam", label: "am_liam", language: "en-US" },
  { id: "am_michael", label: "am_michael", language: "en-US" },
  { id: "am_onyx", label: "am_onyx", language: "en-US" },
  { id: "am_puck", label: "am_puck", language: "en-US" },
  { id: "am_santa", label: "am_santa", language: "en-US" },
  { id: "bf_alice", label: "bf_alice", language: "en-GB" },
  { id: "bf_emma", label: "bf_emma", language: "en-GB" },
  { id: "bf_isabella", label: "bf_isabella", language: "en-GB" },
  { id: "bf_lily", label: "bf_lily", language: "en-GB" },
  { id: "bm_daniel", label: "bm_daniel", language: "en-GB" },
  { id: "bm_fable", label: "bm_fable", language: "en-GB" },
  { id: "bm_george", label: "bm_george", language: "en-GB" },
  { id: "bm_lewis", label: "bm_lewis", language: "en-GB" },
  { id: "jf_alpha", label: "jf_alpha", language: "ja" },
  { id: "jf_gongitsune", label: "jf_gongitsune", language: "ja" },
  { id: "jf_nezumi", label: "jf_nezumi", language: "ja" },
  { id: "jf_tebukuro", label: "jf_tebukuro", language: "ja" },
  { id: "jm_kumo", label: "jm_kumo", language: "ja" },
  { id: "zf_xiaobei", label: "zf_xiaobei", language: "zh" },
  { id: "zf_xiaoni", label: "zf_xiaoni", language: "zh" },
  { id: "zf_xiaoxiao", label: "zf_xiaoxiao", language: "zh" },
  { id: "zf_xiaoyi", label: "zf_xiaoyi", language: "zh" },
  { id: "zm_yunjian", label: "zm_yunjian", language: "zh" },
  { id: "zm_yunxi", label: "zm_yunxi", language: "zh" },
  { id: "zm_yunxia", label: "zm_yunxia", language: "zh" },
  { id: "zm_yunyang", label: "zm_yunyang", language: "zh" },
  { id: "ef_dora", label: "ef_dora", language: "es" },
  { id: "em_alex", label: "em_alex", language: "es" },
  { id: "em_santa", label: "em_santa", language: "es" },
  { id: "ff_siwis", label: "ff_siwis", language: "fr" },
  { id: "hf_alpha", label: "hf_alpha", language: "hi" },
  { id: "hf_beta", label: "hf_beta", language: "hi" },
  { id: "hm_omega", label: "hm_omega", language: "hi" },
  { id: "hm_psi", label: "hm_psi", language: "hi" },
  { id: "if_sara", label: "if_sara", language: "it" },
  { id: "im_nicola", label: "im_nicola", language: "it" },
  { id: "pf_dora", label: "pf_dora", language: "pt-BR" },
  { id: "pm_alex", label: "pm_alex", language: "pt-BR" },
  { id: "pm_santa", label: "pm_santa", language: "pt-BR" },
];

export const MARVIS_DEFAULT_VOICE = "conversational_a";

export const LLM_PROVIDERS = [
  { id: "openai-compatible", label: "OpenAI-compatible server" },
  { id: "ollama", label: "Ollama" },
];
